version: "3.8"

services:
  localstack_salt:
    container_name: localstack_salt
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - DEFAULT_REGION=us-east-1
      # - DATA_DIR=/tmp/localstack/data
      - SERVICES=dynamodb,s3,sqs,lambda,apigateway,cloudformation,es,secretsmanager,stepfunctions,sts,iam,ec2,route53,cloudwatch,logs,events
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"